<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.8.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.8.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0-preview.3.24153.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0-preview.3.24153.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Mriguel.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Features\Items\" />
    <Folder Include="Features\Rentals\" />
    <Folder Include="Features\Users\" />
  </ItemGroup>

</Project>
